# .github/workflows/imagepush.yml
name: Docker Image Build and Push

on:
  push:
    branches:
      - main  # workflow triggers automatically on push to main

jobs:
  image_push:
    runs-on: [self-hosted, Windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: echo "IMAGE_NAME=hemaswathi2002/petapp" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          # Build image tagged with commit SHA
          sudo docker build -t $IMAGE_NAME:${GITHUB_SHA} .
          # Tag the same image as 'latest'
          sudo docker tag $IMAGE_NAME:${GITHUB_SHA} $IMAGE_NAME:latest

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Images
        run: |
          sudo docker push $IMAGE_NAME:${GITHUB_SHA}
          sudo docker push $IMAGE_NAME:latest