name: Docker Image Build and Push

on:
  push:
    branches:
      - main  # triggers on push to main

jobs:
  image_push:
    runs-on: [self-hosted, Windows]
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      IMAGE_NAME: hemaswathi2002/petapp

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        shell: pwsh
        run: |
          # Build image tagged with commit SHA
          docker build -t $env:IMAGE_NAME:$env:GITHUB_SHA .
          # Tag the same image as 'latest'
          docker tag $env:IMAGE_NAME:$env:GITHUB_SHA $env:IMAGE_NAME:latest

      - name: Log in to DockerHub
        shell: pwsh
        run: echo $env:DOCKER_PASSWORD | docker login -u $env:DOCKER_USERNAME --password-stdin

      - name: Push Docker Images
        shell: pwsh
        run: |
          docker push $env:IMAGE_NAME:$env:GITHUB_SHA
          docker push $env:IMAGE_NAME:latest